### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Beliefss** [iLGZH-y/Interpolation-for-homework#1]
请问为什么会一直报错：File "e:\代码仓库\Interpolation-for-homework-main\Interpolation-for-homework-main\GUI.py", line 33, in Interpolator
    mask = np.ones(img.shape[:2]) * 255
                   ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mq-yuan** [comment]
注意：line 29, in Interpolator
` img = cv2.imread(img_path)`

请确保该行正确使用 cv2.imread 读取图像。

你可以检查以下两个方面：

路径是否正确： 确保 img_path 变量包含正确的图像文件路径。
文件是否存在： 验证指定路径下是否存在相应的图像文件。

**Comment by Beliefss** [comment]
您好，我是使用您写的界面选取图片的，路径和照片都没有问题，但还是报错，能指点一下为什么吗？

**Comment by mq-yuan** [comment]
你可以在33行前添加一些调试语句，以检查 img 的值。例如：
```
 print(f"img value: {img}") 
```

**Comment by Beliefss** [comment]
问题已解决，主要问题是图片的路径名中不能含有中文。
